### ISSUE TITLE
Příprava na nasazení aplikace ofn-vocabulary-tools

### ISSUE THREAD

**Issue by bindeali** [datagov-cz/ofn-vocabulary-tools-ui#1]
@blcham připravila jsem základní zárodek aplikace **v branchi  _web-app_**:

### Klient (/client)
* Klasický react+typescript front-end s Vite.js
* [Dockerfile](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/client/Dockerfile) je velmi podobný, jako pro OG: standartní npm build a potom distribuce přes nginx na portu 80 (default). 
* Klient má nastavenou komunikaci se serverem prozatím [natvrdo na localhost:5000/api/test v App.tsx:15](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/client/src/App.tsx#L15), přes formulář, ve kterém se nahraje soubor, který si potom klient zpracuje na string a pošle ho přes POST jako text/plain. **Pokud vše funguje, jak má, tak by se měl pod formulářem objevit JSON, co vrací server**.

### Server (/server)
* [Flask](https://flask.palletsprojects.com/en/3.0.x/) aplikace.
* [Dockerfile](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/server/Dockerfile) následuje víceméně stejné kroky jako klient - instalace dependencies + distribuce přes gunicorn (něco jako nginx, ale v Pythonu). Port je **manuálně** nastavený na 8080 pomocí [Dockerfile:5](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/server/Dockerfile#L5) a [gunicorn_config.py:10](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/server/gunicorn_config.py#L10).
* Server poskytuje základní API na [/api/test v app.py:15](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/server/app.py#L15). Na této adrese přijímá POST requesty, kde přijímá text/plain a vrací délku stringu a prvních 10 charů v JSON.
* CORS je nastavený, aby [povoloval vše na /api/* v app.py:8](https://github.com/datagov-cz/ofn-vocabulary-tools/blob/a85a343cc522e0a90a1d02a504d000aff5af8c5d/server/app.py#L8).

### Cíl:
* Připravit docker-compose.yml pro server i klient tak, aby nemusely být absolutní adresy v klientovi psané natvrdo.
* Upravit klienta tak, aby neměl absolutní adresy psané natvrdo (viz odkaz výše na kód klienta).
* ~Upravit docker-compose.yml v sgov-assembly-line tak, aby v sobě měl i tuto aplikaci.~ Nakonec není součástí sgov-assembly-line
* Nasadit na ~testu/~ devu.

Pokud ode mě budeš potřebovat něco udělat nebo upřesnit, piš sem. Díky moc.

**Comment by blcham** [comment]
@bindeali jelikoz tato issue uz neni pro SGoV Assembly Line presunul jsem tady

**Comment by blcham** [comment]
@bindeali deployment by mel fungovat spravne:

![image](https://github.com/datagov-cz/ofn-vocabulary-tools-ui/assets/3962237/34676259-ec93-4950-bbb5-1a325e1bb334)
